---
name: prometheus

# replace with `bosh status --uuid`
director_uuid: CHANGE_ME

releases:
- name: prometheus
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: nginx
  instances: 1
  vm_type: nano
  stemcell: trusty
  azs: [env1]
  networks: [{name: VMNetwork}]
  jobs:
  - name: nginx
    release: prometheus

- name: grafana
  instances: 1
  vm_type: micro
  stemcell: trusty
  persistent_disk_type: 1024
  azs: [env1]
  networks: [{name: VMNetwork}]
  jobs:
  - name: grafana
    release: prometheus
  - name: bosh_dashboards
    release: prometheus
  - name: cloudfoundry_dashboards
    release: prometheus
  - name: system_dashboards
    release: prometheus
  properties:
    grafana:
      dashboards:
        json:
          enabled: true
      prometheus:
        dashboard_files:
          - /var/vcap/packages/cloudfoundry_dashboards/cf_router.json
          - /var/vcap/packages/cloudfoundry_dashboards/cf_uaa.json
          - /var/vcap/packages/cloudfoundry_dashboards/diego_bbs_etcd.json
          - /var/vcap/packages/cloudfoundry_dashboards/diego_health.json
          - /var/vcap/packages/bosh_dashboards/bosh_deployments.json
          - /var/vcap/packages/bosh_dashboards/bosh_jobs.json
          - /var/vcap/packages/bosh_dashboards/bosh_overview.json
          - /var/vcap/packages/bosh_dashboards/bosh_processes.json
          - /var/vcap/packages/system_dashboards/system_disk_performance.json
          - /var/vcap/packages/system_dashboards/system_disk_space.json
          - /var/vcap/packages/system_dashboards/system_overview.json
- name: alertmanager
  instances: 1
  vm_type: micro
  stemcell: trusty
  persistent_disk_type: 1024
  azs: [env1]
  networks: [{name: VMNetwork}]
  jobs:
  - name: alertmanager
    release: prometheus
    properties:
      alertmanager:
        route:
          receiver: default-receiver
        receivers:
          - name: default-receiver

- name: prometheus
  instances: 1
  vm_type: micro
  stemcell: trusty
  persistent_disk_type: 1024
  azs: [env1]
  networks: [{name: VMNetwork}]
  jobs:
  - name: prometheus
    release: prometheus
    properties:
      prometheus:
        scrape_configs:
          - job_name: blackbox
            metrics_path: /probe
            params:
              module:
                - http_2xx
            static_configs:
              - targets:
                - prometheus.io
            relabel_configs:
              - source_labels: [__address__]
                regex: (.*)(:80)?
                target_label: __param_target
                replacement: ${1}
              - source_labels: [__param_target]
                regex: (.*)
                target_label: instance
                replacement: ${1}
              - source_labels: []
                regex: .*
                target_label: __address__
                replacement: localhost:9115
          - job_name: bosh
            scrape_interval: 1m
            scrape_timeout: 1m
            static_configs:
              - targets:
                - localhost:9190
          - job_name: collectd
            static_configs:
              - targets:
                - localhost:9103
          - job_name: consul
            static_configs:
              - targets:
                - localhost:9107
          - job_name: firehose
            static_configs:
              - targets:
                - localhost:9186
          #- job_name: github
          #  static_configs:
          #    - targets:
          #      - localhost:9171
          - job_name: graphite
            static_configs:
              - targets:
                - localhost:9108
          - job_name: haproxy
            static_configs:
              - targets:
                - localhost:9101
          - job_name: mysql
            static_configs:
              - targets:
                - localhost:9104
          - job_name: nats
            static_configs:
              - targets:
                - localhost:9118
          - job_name: node
            file_sd_configs:
              - files:
                - /var/vcap/store/bosh_exporter/bosh_target_groups.json
            relabel_configs:
              - source_labels: [__meta_bosh_job_process_name]
                regex: node_exporter
                action: keep
              - source_labels: [__address__]
                regex: "(.*)"
                target_label: __address__
                replacement: "${1}:9100"
          - job_name: postgres_exporter
            static_configs:
              - targets:
                - localhost:9113
          - job_name: prometheus
            static_configs:
              - targets:
                - localhost:9090
          - job_name: pushgateway
            static_configs:
              - targets:
                - localhost:9091
          - job_name: rabbitmq
            static_configs:
              - targets:
                - localhost:9125
          - job_name: redis
            static_configs:
              - targets:
                - localhost:9121
          - job_name: statsd
            static_configs:
              - targets:
                - localhost:9102
  - name: blackbox_exporter
    release: prometheus
    properties:
      blackbox_exporter:
        config:
          modules:
            http_2xx:
              prober: http
              timeout: 5s
  - name: bosh_exporter
    release: prometheus
    properties:
      bosh_exporter:
        bosh:
          uaa:
            url: https://CHANGE_ME:8443
            client_id: CHANGE_ME
            client_secret: CHANGE_ME
          url: CHANGE_ME
          ca_cert: |+
            -----BEGIN CERTIFICATE-----
            /var/tempest/workspaces/default/root_ca_certificate from OpsManager
            -----END CERTIFICATE-----
          collectors: Deployments,Jobs,ServiceDiscovery
  # - name: cadvisor
  #   release: prometheus
  - name: collectd_exporter
    release: prometheus
  - name: consul_exporter
    release: prometheus
  - name: firehose_exporter
    release: prometheus
    properties:
      firehose_exporter:
        uaa:
          url: https://uaa.CHANGE_ME
          client_id: CHANGE_ME
          client_secret: CHANGE_ME
        doppler:
          url: wss://CHANGE_ME
        web:
          port: 9186
        skip_ssl_verify: true
  - name: github_exporter
    release: prometheus
    properties:
      github_exporter:
        github:
          repos: cloudfoundry-community/prometheus-boshrelease
  - name: graphite_exporter
    release: prometheus
  - name: haproxy_exporter
    release: prometheus
  #- name: kube_state_metrics_exporter
  #  release: prometheus
  #- name: mysqld_exporter
  #  release: prometheus
  - name: nats_exporter
    release: prometheus
  #- name: node_exporter
  #  release: prometheus
  #- name: postgres_exporter
  #  release: prometheus
  - name: pushgateway
    release: prometheus
  - name: rabbitmq_exporter
    release: prometheus
  - name: redis_exporter
    release: prometheus
  - name: statsd_exporter
    release: prometheus

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false
