---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: pcf-prometheus-git
- name: pcf-bosh-creds

params:
  deployment:
  opsman_url:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:

run:
  path: pcf-prometheus-git/pipeline/tasks/delete-prometheus.sh
